spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dev_database
    username: root
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.project.model
  configuration:
    map-underscore-to-camel-case: true